# Final Project

## 把 table groupby
* day
* hour

In [1]:
import warnings; warnings.simplefilter('ignore')
import numpy as np
import json
import pandas as pd
from pandas.io.json import json_normalize

In [2]:
# list all processed table 
processedList = !(ls data/*.csv)

for i, c in enumerate(processedList):
    processedList[i] = "./data/" + c.split('/')[-1]
print('processed json:\n')
#print(processedList.nlstr)
print('-'*20)

processed json:

--------------------

In [3]:
#processedList = processedList[:]

In [4]:
processedList[0]

'./data/2018-12-08-0309.csv'

In [5]:
dropcol = ['app', 'device_id', 'fmt_opt', 'gps_alt', 'gps_fix', 'gps_num', 's_0', 's_1', 's_2', 's_3', 'tick', 'timestamp', 'ver_app', 'ver_format']
table = []
for filename in processedList:
    try:
        data = pd.read_csv(filename, index_col=[0]).drop(columns=dropcol)
        table.append(data)
    except:
        print(filename)
    
tables = pd.concat(table, ignore_index=True)
    
tables.head()

./data/2018-12-16-1324.csv
./data/2018-12-16-1329.csv
./data/2018-12-16-1334.csv
./data/2018-12-16-1339.csv
./data/2018-12-16-1344.csv
./data/2018-12-16-1349.csv
./data/2018-12-16-1354.csv
./data/2018-12-16-1359.csv
./data/2018-12-16-1404.csv
./data/2018-12-16-1409.csv
./data/2018-12-16-1414.csv
./data/2018-12-16-1419.csv
./data/2018-12-16-1424.csv
./data/2018-12-16-1429.csv
./data/2018-12-16-1434.csv
./data/2018-12-16-1439.csv
./data/2018-12-16-1444.csv
./data/2018-12-16-1449.csv
./data/2018-12-16-1454.csv
./data/2018-12-16-1459.csv
./data/2018-12-16-1504.csv
./data/2018-12-16-1509.csv
./data/2018-12-16-1514.csv
./data/2018-12-16-1519.csv
./data/2018-12-16-1524.csv
./data/2018-12-16-1529.csv
./data/2018-12-16-1534.csv
./data/2018-12-16-1539.csv
./data/2018-12-16-1544.csv
./data/2018-12-16-1549.csv
./data/2018-12-16-1554.csv
./data/2018-12-16-1559.csv
./data/2018-12-16-1604.csv
./data/2018-12-16-1609.csv
./data/2018-12-16-1614.csv
./data/2018-12-16-1619.csv
./data/2018-12-16-1624.csv
./data/2018-12-16-1629.csv
./data/2018-12-16-1634.csv
./data/2018-12-16-1639.csv
./data/2018-12-16-1644.csv
./data/2018-12-16-1649.csv
./data/2018-12-16-1654.csv
./data/2018-12-16-1659.csv
./data/2018-12-16-1704.csv
./data/2018-12-16-1709.csv
./data/2018-12-16-1714.csv
./data/2018-12-16-1719.csv
./data/2018-12-16-1724.csv
./data/2018-12-16-1729.csv
./data/2018-12-17-0314.csv

,SiteName,date,gps_lat,gps_lon,s_d0,s_d1,s_d2,s_h0,s_t0,time
0,74DA38EBF78E,2018-12-07,24.765,120.969,0.0,0.0,0.0,70.0,24.62,20:29:58
1,苗栗縣縣立南埔國小,2018-12-07,24.635,120.973,0.0,0.0,0.0,75.0,21.50,20:46:40
2,苗栗縣縣立田美國小,2018-12-07,24.629,121.008,0.0,0.0,0.0,82.0,19.75,20:32:28
3,74DA38B0538C,2018-12-07,0.000,0.000,0.0,0.0,0.0,60.0,29.00,20:44:11
4,changhua18,2018-12-07,23.879,120.362,13.0,13.0,12.0,100.0,24.25,20:36:37

In [6]:
# See number of rows
tables.index

RangeIndex(start=0, stop=5476494, step=1)

In [7]:
tables.describe(include='all', percentiles=[])

,SiteName,date,gps_lat,gps_lon,s_d0,s_d1,s_d2,s_h0,s_t0,time
count,5476494,5476494,5.476494e+06,5.476494e+06,5.476494e+06,5.476494e+06,5.476494e+06,5.476494e+06,5.476494e+06,5476494
unique,2396,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86397
top,新竹縣備品,2018-12-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02:39:31
freq,6281,527315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201
mean,NaN,NaN,2.382809e+01,1.172449e+02,2.419669e+01,2.828287e+01,1.580135e+01,7.472237e+01,2.445139e+01,NaN
std,NaN,NaN,4.211534e+00,2.530314e+01,2.047703e+01,2.478013e+01,1.329931e+01,1.712902e+01,4.178625e+00,NaN
min,NaN,NaN,-6.888000e+00,-1.223150e+02,0.000000e+00,0.000000e+00,0.000000e+00,-8.300000e+01,-1.400000e+01,NaN
50%,NaN,NaN,2.414300e+01,1.206740e+02,2.100000e+01,2.300000e+01,1.400000e+01,7.300000e+01,2.462000e+01,NaN
max,NaN,NaN,5.219600e+01,1.359690e+02,4.760000e+02,7.490000e+02,4.750000e+02,1.510000e+02,5.212000e+01,NaN

In [8]:
#tables.drop(columns=['app', 'fmt_opt', 's_0', 's_1', 's_2', 's_3', 'tick', 'timestamp', 'ver_app', 'ver_format']).describe(include='all')

In [9]:
#df.drop(columns=['app', 'device_id', 'fmt_opt', 'tick', 'timestamp', 'ver_app', 'ver_format']).head()
#data = df.drop(columns=['SiteName', 'date', 'app', 'gps_alt', 'gps_fix', 'gps_num', 'device_id', 's_0', 's_1', 's_2', 's_3', 'fmt_opt', 'tick', 'timestamp', 'ver_app', 'ver_format'])

#origin_df = df.copy()

# change time(HH:MM:SS) to min
time = pd.DatetimeIndex(tables['time'])
tables['hour'] = time.hour
df = tables[['SiteName', 'date', 's_h0', 's_t0', 'time', 'hour', 's_d0', 's_d1', 's_d2']]
df.head()

       SiteName        date   s_h0   s_t0      time  hour  s_d0  s_d1  s_d2
0  74DA38EBF78E  2018-12-07   70.0  24.62  20:29:58    20   0.0   0.0   0.0
1     苗栗縣縣立南埔國小  2018-12-07   75.0  21.50  20:46:40    20   0.0   0.0   0.0
2     苗栗縣縣立田美國小  2018-12-07   82.0  19.75  20:32:28    20   0.0   0.0   0.0
3  74DA38B0538C  2018-12-07   60.0  29.00  20:44:11    20   0.0   0.0   0.0
4    changhua18  2018-12-07  100.0  24.25  20:36:37    20  13.0  13.0  12.0

In [10]:
df.columns

Index(['SiteName', 'date', 's_h0', 's_t0', 'time', 'hour', 's_d0', 's_d1',
       's_d2'],
      dtype='object')

In [11]:
#pp = tables.groupby([ 'date', 'hour']).mean()
pp = df.groupby(['SiteName', 'date', 'hour'], as_index=False).mean()
#pp.loc['2018-12-08']
pp.columns

Index(['SiteName', 'date', 'hour', 's_h0', 's_t0', 's_d0', 's_d1', 's_d2'], dtype='object')

In [12]:
pp

,SiteName,date,hour,s_h0,s_t0,s_d0,s_d1,s_d2
0,28C2DDDD3FFA,2018-12-08,13,100.000000,21.120000,1.642857,0.000000,0.000000
1,28C2DDDD3FFA,2018-12-08,14,100.000000,21.211765,1.588235,0.000000,0.000000
2,28C2DDDD3FFA,2018-12-08,17,100.000000,20.750000,1.857143,0.000000,0.000000
3,28C2DDDD3FFA,2018-12-08,18,100.000000,20.584000,0.300000,0.000000,0.000000
4,28C2DDDD3FFA,2018-12-08,19,100.000000,20.575000,2.000000,0.000000,0.000000
5,28C2DDDD3FFA,2018-12-08,20,100.000000,20.367368,0.315789,0.000000,0.000000
6,28C2DDDD3FFA,2018-12-08,21,100.000000,20.250000,1.923077,0.000000,0.000000
7,28C2DDDD3FFA,2018-12-08,23,100.000000,20.397857,5.357143,0.000000,0.000000
8,28C2DDDD3FFA,2018-12-09,0,100.000000,20.532727,3.727273,0.000000,0.000000
9,28C2DDDD3FFA,2018-12-09,1,100.000000,20.750000,6.000000,0.000000,0.000000
10,28C2DDDD3FFA,2018-12-09,2,100.000000,21.199444,3.388889,0.000000,0.000000
11,28C2DDDD3FFA,2018-12-09,3,100.000000,21.250000,2.000000,0.000000,0.000000
12,28C2DDDD3FFA,2018-12-09,4,100.000000,21.750000,0.000000,0.000000,0.000000
13,28C2DDDD3FFA,2018-12-09,5,100.000000,21.802500,1.875000,0.000000,0.000000
14,28C2DDDD3FFA,2018-12-09,6,100.000000,21.500000,2.000000,0.000000,0.000000
15,28C2DDDD3FFA,2018-12-09,7,100.000000,21.490000,2.076923,0.000000,0.000000
16,28C2DDDD3FFA,2018-12-09,8,100.000000,21.250000,2.250000,0.000000,0.000000
17,28C2DDDD3FFA,2018-12-09,9,100.000000,21.160000,2.615385,0.000000,0.000000
18,28C2DDDD3FFA,2018-12-09,10,100.000000,21.250000,13.384615,0.000000,0.000000
19,28C2DDDD3FFA,2018-12-09,11,100.000000,21.370000,2.000000,0.000000,0.000000
20,28C2DDDD3FFA,2018-12-09,12,100.000000,21.698182,1.136364,0.000000,0.000000
21,28C2DDDD3FFA,2018-12-09,14,100.000000,22.120000,2.461538,0.000000,0.000000
22,28C2DDDD3FFA,2018-12-09,15,100.000000,22.120000,10.000000,0.000000,0.000000
23,28C2DDDD3FFA,2018-12-09,17,100.000000,22.500000,1.000000,0.000000,0.000000
24,28C2DDDD3FFA,2018-12-09,19,100.000000,22.843889,0.055556,0.000000,0.000000
25,28C2DDDD3FFA,2018-12-09,21,100.000000,23.123333,1.333333,0.000000,0.000000
26,28C2DDDD3FFA,2018-12-09,22,100.000000,23.286667,5.333333,0.000000,0.000000
27,28C2DDDD3FFA,2018-12-13,11,100.000000,20.120000,22.000000,0.000000,0.000000
28,28C2DDDD3FFA,2018-12-13,12,100.000000,20.120000,24.000000,0.000000,0.000000
29,28C2DDDD3FFA,2018-12-13,13,100.000000,20.120000,20.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
458700,雲林縣立饒平國小,2018-12-17,4,52.200000,24.974000,31.400000,37.200000,20.900000
458701,雲林縣立饒平國小,2018-12-17,5,49.923077,25.256154,30.923077,37.153846,20.307692
458702,雲林縣立饒平國小,2018-12-17,6,48.666667,25.500000,34.476190,43.476190,23.000000
458703,雲林縣立饒平國小,2018-12-17,8,50.625000,24.975000,44.000000,56.375000,30.000000
458704,雲林縣立饒平國小,2018-12-17,9,52.700000,24.136000,45.700000,58.400000,31.400000
458705,雲林縣立饒平國小,2018-12-17,10,52.000000,23.750000,43.000000,55.000000,29.000000
458706,雲林縣立饒平國小,2018-12-17,11,50.466667,23.430667,39.866667,50.866667,26.400000
458707,雲林縣立饒平國小,2018-12-17,12,50.000000,23.250000,40.000000,51.000000,27.000000
458708,雲林縣立饒平國小,2018-12-17,13,49.000000,22.910714,29.500000,35.428571,20.571429
458709,雲林縣立饒平國小,2018-12-17,14,48.000000,22.516000,22.000000,25.266667,16.000000
458710,雲林縣立饒平國小,2018-12-17,16,53.846154,21.750000,36.615385,45.461538,24.769231
458711,雲林縣立饒平國小,2018-12-17,17,59.000000,21.630833,43.500000,55.583333,29.083333
458712,雲林縣立饒平國小,2018-12-17,18,60.000000,21.370000,43.000000,56.000000,29.000000
458713,雲林縣立饒平國小,2018-12-17,19,62.500000,21.038333,43.916667,56.666667,29.250000
458714,雲林縣立饒平國小,2018-12-17,20,63.000000,21.000000,47.000000,60.000000,31.000000
458715,雲林縣立饒平國小,2018-12-17,21,60.000000,20.870000,45.000000,58.500000,29.500000
458716,雲林縣立饒平國小,2018-12-17,22,61.666667,20.708333,45.166667,59.166667,30.833333
458717,雲林縣立饒平國小,2018-12-17,23,53.000000,20.370000,31.000000,35.000000,22.000000
458718,雲林縣立饒平國小,2018-12-18,0,51.714286,21.210000,28.000000,32.285714,19.285714
458719,雲林縣立饒平國小,2018-12-18,1,55.272727,22.090000,35.545455,43.818182,24.727273
458720,雲林縣立饒平國小,2018-12-18,2,59.538462,23.254615,40.307692,51.923077,27.307692
458721,雲林縣立饒平國小,2018-12-18,3,61.833333,24.747500,42.916667,55.916667,28.000000
458722,雲林縣立饒平國小,2018-12-18,4,60.050000,25.351500,46.300000,61.300000,30.600000
458723,雲林縣立饒平國小,2018-12-18,6,56.666667,26.343333,47.583333,63.416667,31.416667
458724,雲林縣立饒平國小,2018-12-18,7,58.800000,26.000000,48.800000,63.800000,32.000000
458725,雲林縣立饒平國小,2018-12-18,8,58.000000,25.350000,35.600000,45.600000,24.400000
458726,雲林縣立饒平國小,2018-12-18,9,57.200000,25.024000,31.800000,38.400000,21.600000
458727,雲林縣立饒平國小,2018-12-18,10,63.000000,24.500000,31.000000,36.000000,21.000000
458728,雲林縣立饒平國小,2018-12-18,11,65.500000,23.985000,44.300000,57.300000,30.700000
458729,雲林縣立饒平國小,2018-12-18,12,66.363636,23.826364,49.454545,64.818182,34.090909

## 完成！
* 把 dataframe 寫回 csv!

In [13]:
newtablename = 'pm25_grouped.csv'
pp.to_csv(newtablename, sep=',', index=False)

## Data Partition
* For each input attribute
    * 80% data for training
    * 20% data for testing

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

row = ['lm1', 'lm2', 'lm3', 'lm4', 'lm5', 'lm6', 'lm7']
col = ['MSE', 'R2', 'bias', 'weight']
regResult = pd.DataFrame(index=row, columns=col)

inputNum = len(df.columns)-1

X, y = df.iloc[:, 0:inputNum], df.iloc[:, inputNum:inputNum+1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Simple Linear Regression
   * iteratively train linear model with each attribute

In [ ]:
from sklearn.linear_model import LinearRegression

fig, axes = plt.subplots(2, 3, figsize=(24, 18), sharey=True)
#axes[2][2].set_visible(False)

# Put train/test data to DataFrame to draw plot
Train = pd.concat([X_train, y_train], axis=1)
Test = pd.concat([X_test, y_test], axis=1)
    
for i in range(0, inputNum-2):

    """ simple linear regression by sklearn function"""

    # Train linear model by training set
    reg1 = LinearRegression().fit(X_train.iloc[:, i:i+1], y_train)
    
    # Prediction
    y_pred_lm = reg1.predict(X_test.iloc[:, i:i+1])
    Test['y_pred_lm'] = y_pred_lm

    # Plot outputs    
    plotRow = i//3
    plotCol = i%3
    
    sns.set(font_scale=1)
    sns.regplot(x=Test.columns[i], y='y_pred_lm', 
                data=Test, label='regression', 
                marker='.', line_kws={"linewidth": 2 },
                ax=axes[plotRow][plotCol])
    
    sns.set(font_scale=1)
    sns.scatterplot(x=Test.columns[i], y=Test.columns[-2], 
                    data=Test, label='scatter', 
                    ax=axes[plotRow][plotCol])

    
    # Record metrics
    regResult.iloc[i, 0] = mean_squared_error(y_test, y_pred_lm)
    regResult.iloc[i, 1] = r2_score(y_test, y_pred_lm)
    regResult.iloc[i, 2] = reg1.intercept_[0]
    regResult.iloc[i, 3] = reg1.coef_[0]

In [ ]:
regResult

In [ ]:
Test.columns

In [ ]:
degree_num = 5
row = []

for degree in range(1, degree_num+1):
    row.append('ridge'+str(degree))
    
#row = ['ridge1', 'ridge2', 'ridge3', 'ridge4', 'ridge5']
col = ['1-MSE', 'R2']
regResult = pd.DataFrame(index=row, columns=col)

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

plt.figure(figsize=(12,12))
T = np.linspace(X_test.min().min(), X_test.max().max(), 7625)[:, np.newaxis]
plt.scatter(T, y_test, color='navy', s=30, marker='o', label="training points")

colors = ['red', 'orange', 'teal', 'yellowgreen', 'gold']
lw = 2
for count, degree in enumerate(range(1,degree_num+1)):
    model = make_pipeline(PolynomialFeatures(degree), Ridge())
    model.fit(X_train.iloc[:, :-2], y_train)
    y_polyRidge = model.predict(X_test.iloc[:, :-2])
    regResult.iloc[count] = 1-mean_squared_error(y_test, y_polyRidge), r2_score(y_test, y_polyRidge)
                        
    plt.plot(T, y_polyRidge, color=colors[count], linewidth=lw, label="degree %d" % (degree))
plt.legend()
plt.show()
regResult

In [ ]:
regResult

In [ ]:
np.sort(X_test.iloc[:, :-2].values.reshape(1,-1))

## Compare 10 regression model
* Stochastic Gradient Descent
* k-NN
* SVM with 
    * linear kernel
    * RBF kernel
* Gaussian Procress with
    * RBF kernel
    * Dot Product kernel
* Decision Tree
* Random Forest
* AdaBoost
* Neural Net(Perceptron)

In [ ]:

import warnings; warnings.simplefilter('ignore')
import numpy as np
import pandas as pd


# Preprocess
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import datasets


# import regressors
# for regressors, score function is R2-score in sklearn.metrics
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, DotProduct, WhiteKernel
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.neural_network import MLPRegressor

# import MSE
from sklearn.metrics import mean_squared_error


# Result
col = ['model', 'MSE', 'R2']
regResult = pd.DataFrame(columns=col)


# Regressor List
regressornames = ["SGD", "Nearest Neighbors", "Linear SVR", "RBF SVR", 
         "RBF Gaussian Process", "DotKernel Gaussian Process",
         "Decision Tree", "Random Forest", "AdaBoost", "Neural Net"]

regressors = [
    SGDRegressor(max_iter=1000, tol=1e-3),
    KNeighborsRegressor(3), 
    SVR(kernel='linear', C=1e3),
    SVR(kernel='rbf', C=1e3, gamma=0.1),
    GaussianProcessRegressor(kernel=1.0 * RBF(1.0)),
    GaussianProcessRegressor(kernel=DotProduct() + WhiteKernel()),
    DecisionTreeRegressor(max_depth=5),
    RandomForestRegressor(max_depth=5, n_estimators=10, max_features=2), 
    AdaBoostRegressor(),
    MLPRegressor(hidden_layer_sizes=(5,),
                   learning_rate='adaptive',
                   max_iter=1000,
                   learning_rate_init=0.01,
                   alpha=0.01)
    ]

# Dataset List
iris = datasets.load_iris()
dataName = ["iris"]
X, y = iris.data[:, 0:3], iris.data[:, 3]
myiris = (X, y)

datasets = [myiris]

# iterate over datasets
for ds_cnt, ds in enumerate(datasets):
    X, y = ds
    
    # Standardize
    #X = StandardScaler().fit_transform(X)
    
    # Data Split
    X_train, X_test, y_train, y_test = \
        train_test_split(X, y, test_size=.3, random_state=42)

    # iterate over regressors
    for name, regressor in zip(regressornames, regressors):
        regressor.fit(X_train, y_train)
        score = regressor.score(X_test, y_test)
        y_pred = regressor.predict(X_test)
        print(name, "score: ", score)
        regResult = regResult.append({'model': name, 
                          'MSE': mean_squared_error(y_test, y_pred), 
                          'R2': score}, 
                          ignore_index=True)
        
display(regResult)
print(regResult)

In [ ]:
print(regResult)